# -*- coding: utf-8 -*-
"""CalciumTitaniumOxideQE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QnNoDZ2HuYzUi2UgYhvR0G3NV-fmEiyP
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
from matplotlib import rcParamsDefault
import numpy as np
# %matplotlib inline

plt.rcParams["figure.dpi"]=150
plt.rcParams["figure.facecolor"]="white"
plt.rcParams["figure.figsize"]=(8, 6)

# load data
data = np.loadtxt('csbii3_bands2.dat.gnu')
k = np.unique(data[:, 0])
bands = np.reshape(data[:, 1], (-1, len(k) + 1))

for band in range(len(bands)):
    plt.plot(np.append(k, 1), bands[band, :], linewidth=1, alpha=0.5, color='red')
plt.xlim(min(k), max(k))

# Fermi energy
#plt.axhline(10, linestyle=(0, (5, 5)), linewidth=0.75, color='blue', alpha=0.5)

# High symmetry k-points (check bands_pp.out file)
plt.axvline(0.5000, linewidth=0.75, color='blue', alpha=0.5)
plt.axvline(1.0000, linewidth=0.75, color='k', alpha=0.5)
plt.axvline(1.7071, linewidth=0.75, color='k', alpha=0.5)
plt.axvline(2.5731, linewidth=0.75, color='k', alpha=0.5)
plt.axvline(3.2802, linewidth=0.75, color='k', alpha=0.5)

# Setting y axis to scale

# text labels
plt.xticks(ticks= [0, 0.5000, 1.0000, 1.7071, 2.5731, 3.2802, 3.7802], \
           labels=['L', '$\Gamma$', 'X', 'U', '$\Gamma$', 'Ʌ', 'N'])
plt.ylabel("Energy (eV)")
plt.xlabel("Wave Vector")
plt.ylim((5,10))
#plt.text(2.7, 11, 'Fermi energy', fontsize= 'small')
plt.show()